### PR TITLE
Add Carthage binary JSON for XCFramework

### PR DESCRIPTION
**Pull request by olejnjak**

### CODE REVIEW

**Comment by jgimenez** [comment]
Hi @olejnjak , thanks for contributing. However, I think this file is actually not needed, since when you specify `--use-xcframeworks` Carthage should automatically use the xcframework if available. We tested this some time ago and it worked. Has anything changed since then?

**Comment by olejnjak** [comment]
Well if you need to use `--no-use-binaries` option you don't get XCFramework from GH release and you don't get it from binary JSON either....

**Comment by jgimenez** [comment]
I'm sorry but I don't completely understand... what would be the purpose of using `--no-use-binaries` if Bugfender is distributed as a binary file?

**Comment by olejnjak** [comment]
`--no-use-binaries` means "Don't use binaries attached to github releases and build dependencies instead" and as Bugfender is binary only you have no way how to get it, so if you have binary only dependency it should be distributed using binary JSONs which is currently available for fat framework bundles, but not XCFrameworks...

**Comment by jgimenez** [comment]
I see, thanks.

**Pull request merged**
